version: '3'
services:
  front-end:
    build:
      context: .
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task4
    # ports:
    #   - "8080:80"
    depends_on:
      - back-end

  back-end:
    build:
      context: .
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task4
    # ports:
    #   - "5252:5252"
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task5
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
